### ISSUE TITLE
Bad Magic Number on Python 3.6 - Heroku Deployment

### ISSUE THREAD

**Issue by SylvainLosey** [oesah/bexio-api-python-client#1]
* Bexio API Python Client version: 0.1.4
* Django version: 2.0.3
* Python version: 3.6.4
* Operating System: MacOS

### Description

When deploying to Heroku I get a Bad magic number error when loading Bexiopy, and I can’t find any way to fix it. Both my localy installed python and Heroku run on version 3.6.4. I have tried deleting pyc files, deploying with and without them but that doesn’t change anything.

### What I Did

```
Environment:


Request Method: GET
Request URL: https://oust-admin.herokuapp.com/bexiopy/auth/

Django Version: 2.0.3
Python Version: 3.6.4
Installed Applications:
['nested_admin',
 'admin_interface',
 'colorfield',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'whitenoise.runserver_nostatic',
 'django.contrib.staticfiles',
 'django_celery_beat',
 'django_celery_results',
 'import_export',
 'bexiopy.apps.BexiopyConfig',
 'geoposition',
 'django_extensions',
 'phonenumber_field',
 'raven.contrib.django.raven_compat',
 'database']
Installed Middleware:
('raven.contrib.django.middleware.DjangoRestFrameworkCompatMiddleware',
 'raven.contrib.django.middleware.SentryMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')



Traceback:

File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/app/.heroku/python/lib/python3.6/site-packages/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)

File "/app/.heroku/python/lib/python3.6/site-packages/django/views/generic/base.py" in dispatch
  89.         return handler(request, *args, **kwargs)

File "/app/.heroku/python/lib/python3.6/site-packages/bexiopy/views.py" in get
  29.         client = Client()

File "/app/.heroku/python/lib/python3.6/site-packages/bexiopy/api.py" in __init__
  360.         self.load_access_token_from_file()

File "/app/.heroku/python/lib/python3.6/site-packages/bexiopy/api.py" in load_access_token_from_file
  611.             access_token = shelve.open(token_file)

File "/app/.heroku/python/lib/python3.6/shelve.py" in open
  243.     return DbfilenameShelf(filename, flag, protocol, writeback)

File "/app/.heroku/python/lib/python3.6/shelve.py" in __init__
  227.         Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)

File "/app/.heroku/python/lib/python3.6/dbm/__init__.py" in open
  94.     return mod.open(file, flag, mode)

Exception Type: error at /bexiopy/auth/
Exception Value: Bad magic number
```

**Comment by oesah** [comment]
Will take a look this weekend. I am guessing, one component is not compatible with py3.6.

**Comment by SylvainLosey** [comment]
Any idea if it's easy to make it compatible with Python 3.6 ?

**Comment by oesah** [comment]
I published a new version 0.1.5. Can you try that one please? It worked for me locally. You can now also visit the front page and use the link to authenticate. I adjusted that part in the docs.

**Comment by SylvainLosey** [comment]
Great thanks !

I don't think the Bad Magic Error was caused by a Python 3.6 issue. When I tested locally a .bxcred file was created and when pushing to Heroku I didn't remove it from git which caused the issue. Removing it solved this problem.

The other problem with Heroku is that it has an Ephemeral File system so storing the credentials in a shelve file doesn't work. If that can be of any use I adapted the client to store the credentials in JSON in the default Django storage, in my case set to Amazon S3 : 

https://github.com/keranno/bexio-api-python-client

I don't know if that's the best solution to this problem but it seems to work :)

Thanks again for your help and the great client !

**Comment by oesah** [comment]
yeah I will have to find a better way to store the credentials. The Problem with AWS is that most people don't use AWS, so I need a more generic way of doing that. But glad it works now, I will push this repo to production this week for one of my clients, so it will be better tested in real world applications.

Can you send me a merge request with your changes so I can take a look and see if I can implement it?

**Comment by SylvainLosey** [comment]
Yes sure, I just sent a pull request.
