### ISSUE TITLE
Client.access_token can't be loaded from file because '.bxcred' file doesn't exist

### ISSUE THREAD

**Issue by Verth-Elone** [oesah/bexio-api-python-client#3]
* Bexio API Python Client version: 0.1.5
* Django version: -
* Python version: 3.6
* Operating System: Windows 10 Pro 1803

### Description
I have been using bexiopy with Python without Django and getting "code" by myself via splinter (to automate bexio login page) and then using the code with `client.fetch_access_token_with_auth_code(code)`.

The `client.access_token` is reset to empty dictionary every time `client.load_access_token_from_file()` is run - and that is run with every `client.call(...)`.

I have noticed that there are 3 files created in my project directory:
```
.bxcred.bak
.bxcred.dat
.bxcred.dir
```

However, code in Client.load_access_token_from_file() looks like:

```
    def load_access_token_from_file(self):
        """
        Open and return the dictionary of the shelve file.

        Returns:
            dict: :code:`access_token` loaded from file
        """
        token_file = get_setting('BEXIO_CREDENTIALS_FILENAME')
        if os.path.exists(token_file):
            with shelve.open(token_file) as access_token:
                token = dict(access_token)
            access_token.close()
            self.access_token = token
        else:
            # let user know, he needs to authentiate with bexio
            logger.warning(
                "You need to authorize this app with your "
                "bexio instance. Open the following link and "
                "you will be redirected back.\n\n%s" %
                self.get_oauth2_auth_url())
            self.access_token = {}
        return self.access_token
```

and in the settings.py (64):

`_BEXIO_CREDENTIALS_FILENAME = '.bxcred'`

The program never finds the file in the working directory, because shelve creates 3 files with different extensions.

### What I Did

To fix it I applied this change:
```
 if os.path.exists(token_file):
    ...
```

```
 if os.path.exists(f('{token_file}.dat'):
    ...
```

**Comment by oesah** [comment]
@Verth-Elone Closing this, this lib is not maintained at the moment. You can send a PR if you find a solution, but there are easier ways now to talk to the Bexio API. Refer to their official documentation please.
